package.path = "lua/?.lua;" .. package.path
local site = require("aiagentskills_site_kit")
assert(site.home_url() == "https://aiagentskills.net")
assert(site.skills_url() == "https://aiagentskills.net/skills/")
assert(site.submit_url() == "https://aiagentskills.net/submit/")
assert(site.blog_url() == "https://aiagentskills.net/blog/")
assert(site.category_url("agent-workflows") == "https://aiagentskills.net/category/agent-workflows/")
assert(site.skill_url("seo-article-writer") == "https://aiagentskills.net/skill/seo-article-writer/")
assert(site.search_url("codex skills") == "https://aiagentskills.net/skills/?q=codex%20skills")
assert(site.metadata.homepage == "https://aiagentskills.net")
